// Code generated by MockGen. DO NOT EDIT.
// Source: repository.go
//
// Generated by this command:
//
//	mockgen -source=repository.go -destination=repository_mock.go -package=storage
//

// Package storage is a generated GoMock package.
package storage

import (
	context "context"
	reflect "reflect"
	entity "surf_challenge/internal/action/storage/entity"

	gomock "go.uber.org/mock/gomock"
)

// MockRepository is a mock of Repository interface.
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
	isgomock struct{}
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository.
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance.
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// GetActionsByUserID mocks base method.
func (m *MockRepository) GetActionsByUserID(ctx context.Context, userID int64) ([]*entity.Action, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetActionsByUserID", ctx, userID)
	ret0, _ := ret[0].([]*entity.Action)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetActionsByUserID indicates an expected call of GetActionsByUserID.
func (mr *MockRepositoryMockRecorder) GetActionsByUserID(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetActionsByUserID", reflect.TypeOf((*MockRepository)(nil).GetActionsByUserID), ctx, userID)
}
